### ISSUE TITLE
Doc description is not updated

### ISSUE THREAD

**Issue by pjgg** [quarkiverse/quarkiverse#206]
Hi,  I have [updated](https://github.com/quarkiverse/quarkus-hivemq-client/blob/main/runtime/src/main/resources/META-INF/quarkus-extension.yaml#L3C14-L3C73) my extension doc description on my Quarkus extension YAML file, but I don´t see any effect on the website. 

I would expect the following sites updated, according to these changes:
- https://quarkus.io/extensions/io.quarkiverse.hivemqclient/quarkus-hivemq-client/
- https://quarkus.io/extensions/?search-regex=hivemq

Instead of `Quarkus - Hivemq Client Implementation of MQQ Messaging` I would expect `Transform your business with the most trusted MQTT platform`. 

The changes were made following this documentation: https://quarkus.io/guides/extension-metadata#quarkus-extension-yaml

> Description that can be displayed to users. In this case, the description was copied from the pom.xml of the extension module but it could also be provided in the template file.

So ok... looks like could be also on the pom `description` field but, based on the docs looks like is also possible to have this extension description on the `quarkus-extension-yaml` file

WDYT ?

**Comment by holly-cummins** [comment]
It looks like the description is now showing as intended on https://quarkus.io/extensions/io.quarkiverse.hivemqclient/quarkus-hivemq-client/:

<img width="688" alt="image" src="https://github.com/quarkiverse/quarkiverse/assets/11509290/d6ffcaed-db23-402b-971f-fafec98d969d">

I suspect the original delay happened because we show the description of the latest release, rather than reading it from the GitHub source code. (Some other things we do read dynamically, like issue counts, but the metadata, including description, is intended to be specific to a release.)
